### ISSUE TITLE
Holaa

### ISSUE THREAD

**Issue by BaltaL0ki** [jpgelmi/Servel-ripper#1]
Hola Juan de casualidad no tienes la data? al parecer ya no está disponible, saludos.

**Comment by jpgelmi** [comment]
Hola!

El proyecto extrae todos los padrones electorales del Servel que en su momento estaban en https://cdn.servel.cl/padron/A01101.pdf donde había que cambiar el ultimo termino (A01101.pdf) para obtener el padrón deseado. Actualmente la información no está disponible en el Servel, por lo que si uno corre el proyecto, este no va a funcionar :( (por eso la data no está disponible)

**Comment by BaltaL0ki** [comment]
gracias por la explicación, no me podrias compartir todos los pdfs ?

**Comment by jpgelmi** [comment]
El Servel el 22 de septiembre publicó los padrones electorales definitivos para la elecciones del 21 de Noviembre, voy a editar el scraper para los pueda descargar, no pude subir los padrones electorales anteriores ya que estos pesan en total más de 6 GB.

Acá te dejo el link del Servel
https://servel.cl/padron-electoral-definitivo-y-nomina-de-inhabilitados-elecciones-generales-2021/

**Comment by jpgelmi** [comment]
Listo! el proyecto está listo para obtener los padrones de las elecciones de diputados y gobernadores 2021. Cabe recalcar que esta vez el Servel no publicó las direcciones y locales de votación dado que esa información podría cambiar. Ahora quiero cambiar partes del proyecto para que pueda manejar de mejor manera la descarga de los datos, quizás trabajar con descargas paralelas y asíncronas también trabajar un poco en el _error handling_
